version: "3"
services:
  influxdb:
    image: influxdb:latest
    volumes:
      - ./influxdb/data:/var/lib/influxdb/
      - ./influxdb/config/:/etc/influxdb/
    ports:
      - "8086:8086"
      - "8082:8082"
      - "8089:8089/udp"

  chronograf:
    image: chronograf:latest
    volumes:
      - ./chronograf/data/:/var/lib/chronograf/
    ports:
      - "8888:8888"
    depends_on:
      - kapacitor
      - influxdb
      - telegraf

  telegraf:
    image: telegraf
    volumes:
      - ./telegraf/config:/etc/telegraf/
      - ./telegraf/data/:/var/lib/telegraf/
      - /:/hostfs:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - HOST_MOUNT_PREFIX=/hostfs
      - HOST_PROC=/hostfs/proc
    ports:
      - 8186:8186
    depends_on:
      - influxdb

  kapacitor:
    image: kapacitor
    volumes:
      - ./kapacitor/config:/etc/kapacitor/
      - ./kapacitor/data/:/var/lib/kapacitor/
    ports:
      - "9092:9092"
    depends_on:
      - influxdb

  mosquitto:
    image: eclipse-mosquitto
    restart: unless-stopped
    ports:
      - 1883:1883
      - 8080:8080
    volumes:
      - ./mosquitto/:/mosquitto/
